// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sabzishop.Db_Context;

namespace Sabzishop.Migrations
{
    [DbContext(typeof(MyDb))]
    [Migration("20220415142624_thisisisaded")]
    partial class thisisisaded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sabzishop.Models.Category.Category", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Sabzishop.Models.Products.Products", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ISspesial")
                        .HasColumnType("bit");

                    b.Property<long>("categoryid")
                        .HasColumnType("bigint");

                    b.Property<string>("discriptio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("instroe")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("categoryid");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Sabzishop.Models.Slider.Slider", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("discription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("undertitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("slider");

                    b.HasData(
                        new
                        {
                            id = 1L,
                            discription = "این یه نمونه برای شما که هستی ",
                            title = "تله فیزیون1",
                            undertitle = "شپولی جونم"
                        },
                        new
                        {
                            id = 2L,
                            discription = "این یه نمونه برای شما که هستی ",
                            title = "تله فیزیون2",
                            undertitle = "شپولی جونم"
                        },
                        new
                        {
                            id = 3L,
                            discription = "این یه نمونه برای شما که هستی ",
                            title = "تله فیزیون3",
                            undertitle = "شپولی جونم"
                        },
                        new
                        {
                            id = 4L,
                            discription = "این یه نمونه برای شما که هستی ",
                            title = "4تله فیزیون",
                            undertitle = "شپولی جونم"
                        },
                        new
                        {
                            id = 5L,
                            discription = "این یه نمونه برای شما که هستی ",
                            title = "تله فیزیون5",
                            undertitle = "شپولی جونم"
                        },
                        new
                        {
                            id = 6L,
                            discription = "این یه نمونه برای شما که هستی ",
                            title = "تله فیزیون6",
                            undertitle = "شپولی جونم"
                        },
                        new
                        {
                            id = 7L,
                            discription = "این یه نمونه برای شما که هستی ",
                            title = "تله فیزیون7",
                            undertitle = "شپولی جونم"
                        },
                        new
                        {
                            id = 8L,
                            discription = "این یه نمونه برای شما که هستی ",
                            title = "تله فیزیون8",
                            undertitle = "شپولی جونم"
                        },
                        new
                        {
                            id = 9L,
                            discription = "این یه نمونه برای شما که هستی ",
                            title = "9 فیزیون",
                            undertitle = "شپولی جونم"
                        });
                });

            modelBuilder.Entity("Sabzishop.Models.Products.Products", b =>
                {
                    b.HasOne("Sabzishop.Models.Category.Category", "Category")
                        .WithMany("ProductsList")
                        .HasForeignKey("categoryid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Sabzishop.Models.Category.Category", b =>
                {
                    b.Navigation("ProductsList");
                });
#pragma warning restore 612, 618
        }
    }
}
